trigger:
- main

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    chmod +x mvnw
    ./mvnw clean package
  displayName: 'Compilar aplicación Spring Boot'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'conexion-calendario-api'
    appType: 'webAppLinux'
    appName: 'Calendario-apiweb'
    package: 'target/*.jar'
  displayName: 'Desplegar API en Azure App Service'