trigger:
- main

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    - script: |
    pwd
    ls
    cd apiCalendario/apicalendario
    pwd
    ls
    chmod +x mvnw
    ./mvnw clean package
  displayName: 'Compilar aplicación Spring Boot'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'apiCalendario/apicalendario/target'
    Contents: '*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copiar archivo JAR'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publicar artefacto'